#!/bin/bash

action=$1  ; shift
stackid=${1%.yml} ; shift

cmd="
    aws cloudformation $action-stack \
    --stack-name $stackid \
    $( [[ "$action" == delete ]] || echo "--template-body file://$stackid.yml" ) \
    --region=us-west-2 $@  \
    $( [[ "$action" == delete ]] || echo "--capabilities CAPABILITY_NAMED_IAM" ) 
"
echo $cmd
$cmd

exit $?

