Description: >
  Simon Wall / MoopyGlue

Parameters:
  networkStack:
      Description: Single Parameter that we are passing with the env name.
      Type: String
      Default: "udcap-base"

Resources:

  #===============================================================
  # Security Groups
  #===============================================================

  SGBastion:
    Type: AWS::EC2::SecurityGroup
    Properties: 
        VpcId:
          Fn::ImportValue: !Sub "${networkStack}-vpcid"
        GroupDescription: Security Group Bastion Host
        SecurityGroupIngress:
        - IpProtocol: tcp  # ssh access to bastion host from single IP
          FromPort: 22
          ToPort: 22
          CidrIp: 82.34.193.156/32
        SecurityGroupEgress:
        - IpProtocol: tcp # ssh access to stack servers
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0            

  Bastion:
    Type: AWS::EC2::Instance
    Properties: 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          export DEBIAN_FRONTEND=noninteractive
          apt upgrade -y
          sudo snap install kubectl --classic
          sudo snap install aws-cli --classic
      # Amazon Image ami-003634241a8fcdec0 : Ubuntu Server 18.04 LTS
      # NOTE: this image uses account 'ubuntu' instead of 'ec2-user'
      ImageId: ami-003634241a8fcdec0
      KeyName: udcap-ssh-bastion
      InstanceType: t3.micro
      SecurityGroupIds : [ !GetAtt SGBastion.GroupId ]
      SubnetId: 
        Fn::ImportValue: !Sub "${networkStack}-bastion-subnet"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'

Outputs:

  BastionDNS:
      Description: A reference to the software external URL for thsi cluster
      Value: !GetAtt Bastion.PublicDnsName
      Export:
          Name: !Sub ${networkStack}-bastion-dns

  BastionIp:
      Description: A reference to the software external URL for thsi cluster
      Value: !GetAtt Bastion.PublicIp
      Export:
          Name: !Sub ${networkStack}-bastion-ip
