version: '3'
services:
    jenkins:
        container_name: jenkins
        image: jenkins-ansible
        build:
            context: jenkins-ansible
        ports:
            - "9080:8080"
            - "51000:50000"
        volumes:
            - "$HOME/jenkins_home:/var/jenkins_home"
        networks:
            - net
networks:
    net:
