apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eyes
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eyes
    spec:
      containers:
      - name: eyes
        image: qmkey/udacity:capstone-eyes-server
        command: ["/app/entrypoint.bash"]
        args: ["-h","hubaddress:7777","carrier"]
        ports:
        - containerPort: 6001
